before:
  hooks:
    - go mod download

build:
  ldflags:
    - -s -w
  binary: ovh-ddns-update
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386

archives:
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      386: i386
      darwin: macOS
