before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
    binary: ovh-ddns-update
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7

  - id: macos
    ldflags:
      - -s -w
    binary: ovh-ddns-update
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      386: i386
      darwin: macOS
